CREATE TABLE IF NOT EXISTS jobs (
    "JOBCREATEDATE" TIMESTAMP,
    "JOBDATE" TIMESTAMP,
    "JOBIDENTIFIER" INT PRIMARY KEY,
    "JOBSTATUS" VARCHAR(20) CHECK ("JOBSTATUS" IN ('NO SUCCESS', 'SUCCESS')),
    "LOCATION" VARCHAR(255),
    "REVENUE" DECIMAL(10, 2),
    "SERVICENAME" VARCHAR(255),
    "USERID" BIGINT
    );